[package]
name = "tomb-crypt"
license = "LicenseRef-LICENSE.txt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Common dependencies
base64 = { version = "^0.21" }
async-trait = "0.1.71"
serde = "1.0.183"
jwt-simple = { version = "0.11.6" }
rand = "0.8.5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
openssl = { version = "^0.10", features = ["vendored"] }
openssl-hkdf = { version = "^0.2" }
tokio = { version = "^1", default-features = false, features = ["rt", "rt-multi-thread", "test-util", "tokio-macros", "macros"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
console_error_panic_hook = "^0.1"
gloo = { version = "0.8.1", features = [ "utils", "console" ] }
js-sys = "^0.3"
pem = "^2"
wasm-bindgen-futures = "^0.4"
wasm-bindgen = "^0.2"
web-sys = { version = "^0.3", features = [
  "Crypto",
  "CryptoKey",
  "CryptoKeyPair",
  "SubtleCrypto",
  "EcKeyGenParams",
  "EcdhKeyDeriveParams",
  "HkdfParams"
]}

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "^0.3"

