[package]
name = "tomb-crypt"
license = "LicenseRef-LICENSE.txt"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "^0.1"
base64 = { version = "^0.21" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
openssl = { version = "^0.10", features = ["vendored"] }
openssl-hkdf = { version = "^0.2" }
tokio = { version = "^1", default-features = false, features = ["macros", "rt", "rt-multi-thread", "test-util", "tokio-macros"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "^0.1"
gloo = { version = "^0.8", features = [ "console", "utils" ] }
js-sys = "^0.3"
pem = "^2"
wasm-bindgen-futures = "^0.4"
wasm-bindgen = "^0.2"
web-sys = { version = "^0.3", features = [
  "Crypto",
  "CryptoKey",
  "CryptoKeyPair",
  "SubtleCrypto",
  "EcKeyGenParams",
  "EcdhKeyDeriveParams",
  "HkdfParams"
]}

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "^0.3"

